project:
  type: website
  output-dir: docs

website:
  title: "Research, data and web apps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Favorites.qmd

format:
  html:
    theme: quartz
    mainfont: arial
    fontsize: 1.5rem
    #fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new
    css: styles.css
    toc: true



